list = [64, 24, 1, 35, 2, 2, 3, 4, 5, 7]
print(list)
# list.append(98)
# print(list)
# list.append(100)
# print(list)
# list.sort()
# print(list)
# list.sort(reverse=True)
# print(list)
# list.reverse()
# print(list)
# print(list.index(2))
# print(list)
# print(list.count(2))
print(list.insert(2, 985))
print(list)
m = [900, 1000, 1100]
# list.extend(m)
# print(list)
# list.sort()
# print(list)
c = list + m
print(c)